---
title: "BIOSTAT 650 Project"
author: "Jaehoon Kim"
date: "2024-11-17"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("sas7bdat")
library("corrplot")
library("gtsummary")
library("dplyr")
library("ggplot2")
library("data.table")
library("car")
library("NHANES")
library("olsrr")
```




```{r datasetup 1}
df = NHANES

```

Initial data exploration of covariates that had a relation to SexAge were difficult to perform a correlation plot due to being factors.
```{r EDA}
covariates = c("SexAge","Gender","HHIncome","Education","PhysActive","SameSex","AlcoholYear","RegularMarij","HardDrugs")
sapply(df[, covariates], is.factor)
#M = cor(df[, covariates])
#corrplot(M, method = 'number')
```



```{r model 1}
model <- lm(BPSys1 ~ Age+Gender+Poverty+BMI+SleepHrsNight+PhysActiveDays+SmokeNow+AlcoholYear+HardDrugs, df)
summary(model)

```

```{r model 2,3}
model <- lm(SexAge ~ Depressed+LittleInterest+HealthGen+Gender+HHIncome+Education+PhysActive+RegularMarij+HardDrugs+RegularMarij*HardDrugs+Depressed*HardDrugs+SmokeAge, df)
summary(model)
model <- lm(SexAge ~ RegularMarij+HardDrugs+RegularMarij*HardDrugs, df)
summary(model)
```

```{r model 3-1}
model <- lm(SexAge ~ Gender+HHIncome+Education+SameSex+PhysActive+RegularMarij+HardDrugs+RegularMarij*HardDrugs, df)
summary(model)
```

```{r model 4}
model <- lm(SexNumPartnLife ~ Gender+HHIncome+Education+PhysActive+RegularMarij+HardDrugs+RegularMarij*HardDrugs, df)
summary(model)
```

```{r model 5}
model <- lm(SexNumPartnLife ~ Gender+HHIncome+Education+PhysActive+SameSex+RegularMarij+HardDrugs+RegularMarij*HardDrugs, df)
summary(model)
```

Created new variable and log transformed due to extreme skewness
```{R New variable}
hist(df$SexAge)
sort(unique(df$SexAge))
typeof(df$SexAge)
subset(df, SexAge == 9 & !is.na(SexAge))$SexNumPartnLife
hist(df$SexNumPartYear)
hist(df$SexNumPartYear[df$SexNumPartYear < 20])
sort(unique(df$SexNumPartYear))

hist(df$SexNumPartnLife)
hist(df$SexNumPartnLife[df$SexNumPartnLife < 30])

unique(df$SexAge)
df = mutate(df, AvgSexFreq = log((Age-SexAge)/SexNumPartnLife))
hist(df$AvgSexFreq)
boxplot(df$AvgSexFreq)
```

```{R New variable test}
#Remove negative infinity
df$AvgSexFreq[is.infinite(df$AvgSexFreq)] = NA
#unique(df$AvgSexFreq)

model <- lm(AvgSexFreq ~ Gender+HHIncome+Education+PhysActive+SameSex+AlcoholYear+RegularMarij+HardDrugs+RegularMarij*HardDrugs, df)
summary(model)

#model <- lm(AvgSexFreq ~ #Gender+HHIncome+Education+PhysActive+SameSex+AlcoholYear+RegularMarij+HardDrugs+#RegularMarij*HardDrugs+RegularMarij*AlcoholYear, df)
#summary(model)

```
```{r systematic differences of missing values}

library(ggplot2)
library(tidyr)
#Add new column based on missingness
df$missingness <- ifelse(is.na(df$AvgSexFreq), "Missing", "Not Missing")
covariates = c("Gender","HHIncome","Education","PhysActive","SameSex","AlcoholYear","RegularMarij","HardDrugs")

```
```{r missigness graphs}
library(gridExtra)
p1 = ggplot(data = df, mapping=aes(x=Gender, fill=as.factor(missingness)))+
  geom_bar(stat="count")+
  scale_fill_manual(values = c("gray", "red"))
p2 = ggplot(data = df, mapping=aes(x=HHIncome, fill=as.factor(missingness)))+
  geom_bar(stat="count")+
  scale_fill_manual(values = c("gray", "red"))
p3 = ggplot(data = df, mapping=aes(x=Education, fill=as.factor(missingness)))+
  geom_bar(stat="count")+
  scale_fill_manual(values = c("gray", "red"))
p4 = ggplot(data = df, mapping=aes(x=PhysActive, fill=as.factor(missingness)))+
  geom_bar(stat="count")+
  scale_fill_manual(values = c("gray", "red"))

grid.arrange(p1,p2,p3,p4, nrow=5)
```

```{r missingness plot 2}
p6 = ggplot(data = df, mapping=aes(x=SameSex, fill=as.factor(missingness)))+
  geom_bar(stat="count")+
  scale_fill_manual(values = c("gray", "red"))
p7 = ggplot(data = df, mapping=aes(x=AlcoholYear, fill=as.factor(missingness)))+
  geom_bar(stat="count")+
  scale_fill_manual(values = c("gray", "red"))
p8 = ggplot(data = df, mapping=aes(x=RegularMarij, fill=as.factor(missingness)))+
  geom_bar(stat="count")+
  scale_fill_manual(values = c("gray", "red"))
p9 = ggplot(data = df, mapping=aes(x=HardDrugs, fill=as.factor(missingness)))+
  geom_bar(stat="count")+
  scale_fill_manual(values = c("gray", "red"))
grid.arrange(p6, p7, p8, p9, nrow = 4)
```


```{r Partial SS}
library(car)
car::Anova(lm(AvgSexFreq ~ Gender+HHIncome+Education+PhysActive+SameSex+AlcoholYear+RegularMarij+HardDrugs+RegularMarij*HardDrugs, df), type="III")


```


```{r QQplot}

m1 = lm(AvgSexFreq ~ Gender+HHIncome+Education+PhysActive+SameSex+AlcoholYear+RegularMarij+HardDrugs+RegularMarij*HardDrugs, df)
m1.res = m1$residuals

car::qqPlot(m1.res)
```

```{r avPlots}

car::avPlots(m1)
```

```{r Residual Plots}


car::residualPlots(m1, type="response")
```

```{r multicolinearity}
#interactions(???)
car::vif(m1, type = 'predictor')
```

```{r outliers}
model.deffits=dffits(m1)
model.CD = cooks.distance(m1)
model.deffits[which.max(model.deffits)]
model.CD[which.max(model.CD)]

```

```{r plot for outlier}
ols_plot_resid_lev(m1)
```

```{r remove outliers}
df2 = df[-c(932, 1059, 1442, 2526, 2738, 2872,3453),]
m2 = lm(AvgSexFreq ~ Gender+HHIncome+Education+PhysActive+SameSex+AlcoholYear+RegularMarij+HardDrugs+RegularMarij*HardDrugs, df2)

summary(m2)
#detect beta change by more than 10 percent?
100*(coef(m1)-coef(m2))/coef(m1)
```

```{r rerun qqplot}
m2.res = m2$residuals

car::qqPlot(m2.res)
```